config/routes.rb
Rails.application.routes.draw do
    
  get 'menu_items/index'
  # 顧客用
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  devise_scope :customer do
    post '/customers/sign_up', to: 'public/registrations#create', as: 'custom_registration'
    delete '/customers/sign_out' => 'devise/sessions#destroy'
  end

  root to: "public/homes#top"
  get '/about' => 'public/homes#about'
  
  scope module: 'customers' do
    resources :cats, only: [:show, :index]
    resources :menu_items, only: [:index]
  end
  
  namespace :public do
    get '/my_page', to: 'customers#show', as: 'my_page'#マイページ
    get 'customers/edit' => 'customers#edit'
    patch 'update' => 'customers#update'#会員情報編集画面
    get 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customer'#退会機能
    get 'quit' => 'customers#quit'#退会画面
    resources :cats, only: [:index, :show]#所属猫一覧画面、所属猫詳細画面
    resources :menu_items, only: [:index]#カフェメニュー一覧
    get '/reservations/new' => 'reservations#new', as: 'new_reservation'#予約情報入力画面
    post '/reservations' => 'reservations#create', as: 'reservations'
    get 'reservations/thanks' => 'reservations#thanks', as: 'thanks_reservation'#サンクス画面
    get 'my_page/reservations' => 'reservations#index', as: 'my_page_reservations'#予約情報入力画面
    resources :reservations, only: [:show]#予約情報確認画面
  end
  
  
  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  devise_scope :admin do
    delete '/admin/sign_out' => 'devise/sessions#destroy'
  end
   
  namespace :admin do
    root :to => 'homes#top'
    resources :customers, only: [:index, :show, :edit, :update, :destroy]#会員画面
    resources :cats, only: [:show, :index, :new, :create, :edit, :update, :destroy]#所属猫画面
    resources :menu_items, only: [:index, :new, :create, :edit, :update, :destroy]#カフェメニュー画面
    resources :reservations, only: [:index, :show]#予約一覧画面、予約詳細画面
    delete 'cats'=> 'cats#destroy'#登録猫削除画面
    delete 'menu_items'=> 'menu_items#destroy'
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    belongs_to :customer
    has_many :reservation_status
    
    enum status: { ご予約中: 0, 訪問済み: 1, キャンセル: 2}
    
    validates :number_of_people,  presence: true
    validates :date_and_time, presence: true
    validates :customer, presence: true
end

app/controllers/admin/reservations_controller.rb
class Admin::ReservationsController < ApplicationController
    before_action :authenticate_admin!
    
    def index
        @search=Reservation.includes(:customer).ransack(params[:q])
        @reservations=@search.result.page(params[:page]).per(20)
    end
    
    def show
        @reservation=Reservation.find(params[:id])
        @customer = @reservation.customer
    end
    
    def update
        @reservation=Reservation.find(params[:id])
        @customer = @reservation.customer
    end
    
    private
        def reservation_params
            params.require(:reservation).permit(:customer_id, :date_and_time, :number_of_people, :status)
        end
end

app/views/admin/reservations/index.html.erb
<div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <h2>予約一覧</h2>
            <div class="order-table">
                    <table class="table table-hover table-inverse">
                        <thead>
                            <tr>
                                <th>予約者氏名</th>
                                <th>予約日時</th>
                                <th>訪問人数</th>
                                <th>訪問状況</th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @reservations.each do |reservation| %>
                            <tr>
                                <% if reservation.customer.present? %>
                                    <td><%= reservation.customer.first_name %><%= reservation.customer.last_name %>様</td>
                                <%else%>
                                    <td>予約者不明</td>
                                <%end%>
                                <td><%= reservation.date_and_time.strftime("%Y-%m-%d %H:%M:%S") %></td>
                                <td><%= reservation.number_of_people %>名様</td>
                                <td><%= reservation.status %></td>
                            </tr>
                            <%end%>
                            <%= paginate @reservations %>
                        </tbody>
                    </table>
            </div>
        </div>
</div>

app/views/admin/reservations/show.html.erb
            <div class="col-xs-10 col-xs-offset-1">
                <div class="row">
                    <div class="col-xs-7">
                    <h2>予約内容詳細</h2>
                    <table class="table table-striped table-light">
                        <tbody>
                            <tr>
                                <th>予約者氏名</th>
                                <td><%= @reservation.customer.last_name %> <%= @reservation.customer.first_name %></td>
                            </tr>
                            <tr>
                                <th>予約日時</th>
                                <td><%= @reservation.date_and_time.strftime("%Y-%m-%d %H:%M:%S") %></td>
                            </tr>
                            <tr>
                                <th>訪問人数</th>
                                <td><%= @reservation.number_of_people %>名様</td>
                            </tr>
                            <tr>
                                <th>支払方法</th>
                                <td><%= @reservation.payment_methods %></td>
                            </tr>
                            <tr>
                                <th>予約ステータス</th>
                                <td><%= form_with model: @reservation, url: admin_reservation_path(@reservation) do |f| %>
                                <%= f.select :reservation_status, ReservationStatus.reserve_statuses.keys.to_a %>
                                <%= f.submit "更新する", class: "btn btn-outline-success" %>
                                <% end %>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    </div>
                </div>
            </div>