config/routes.rb
Rails.application.routes.draw do
    
  get 'menu_items/index'
  # 顧客用
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  devise_scope :customer do
    post '/customers/sign_up', to: 'public/registrations#create', as: 'custom_registration'
    delete '/customers/sign_out' => 'devise/sessions#destroy'
  end

  root to: "public/homes#top"
  get '/about' => 'public/homes#about'
  
  scope module: 'customers' do
    resources :cats, only: [:show, :index]
    resources :menu_items, only: [:index]
  end
  
  namespace :public do
    get '/my_page', to: 'customers#show', as: 'my_page'#マイページ
    get 'customers/edit' => 'customers#edit'
    patch 'update' => 'customers#update'#会員情報編集画面
    get 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customer'#退会機能
    get 'quit' => 'customers#quit'#退会画面
    resources :cats, only: [:index, :show]#所属猫一覧画面、所属猫詳細画面
    resources :menu_items, only: [:index]#カフェメニュー一覧
    get '/reservations/new' => 'reservations#new', as: 'new_reservation'#予約情報入力画面
    post '/reservations' => 'reservations#create', as: 'reservations'
    get 'reservations/thanks' => 'reservations#thanks', as: 'thanks_reservation'#サンクス画面
    get 'my_page/reservations' => 'reservations#index', as: 'my_page_reservations'#予約情報入力画面
    resources :reservations, only: [:show]#予約情報確認画面
  end
  
  
  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  devise_scope :admin do
    delete '/admin/sign_out' => 'devise/sessions#destroy'
  end
   
  namespace :admin do
    root :to => 'homes#top'
    resources :customers, only: [:index, :show, :edit, :update, :destroy]#会員画面
    resources :cats, only: [:show, :index, :new, :create, :edit, :update, :destroy]#所属猫画面
    resources :menu_items, only: [:index, :new, :create, :edit, :update, :destroy]#カフェメニュー画面
    resources :reservations, only: [:index, :show]#予約一覧画面、予約詳細画面
    delete 'cats'=> 'cats#destroy'#登録猫削除画面
    delete 'menu_items'=> 'menu_items#destroy'
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :reservations, dependent: :destroy
         has_one_attached :image
         
    def active_for_authentication?
      super && (self.is_deleted == false)
    end
    
       validates :last_name,  presence: true
       validates :first_name, presence: true
       validates :last_name_kana,  presence: true
       validates :first_name_kana, presence: true
       validates :telephone_number, presence: true
       validates :birthday, presence: true
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
    before_action :authenticate_admin!, only: [:edit,:update,:index, :show]
    
    def index #会員一覧
      @search=Customer.ransack(params[:q])
      @customers=@search.result.page(params[:page])
    end
    
    def show
      @customer=Customer.find(params[:id])
    end
    
    def edit
      @customer=Customer.find(params[:id])
    end
    
    def update
      @customer=Customer.find(params[:id])
      if @customer.update(customer_params)
        flash[:notice_update] ="会員情報を更新しました"
        redirect_to admin_customer_path(@customer)
      else
        render edit_admin_customer_path(@customer)
      end
    end
    
    def destroy
      @customer=Customer.find(params[:id])
      @customer.destroy
      flash.now[:alert]="#{@customer.id}を削除しました"
      redirect_to admin_customers_path
    end
    
  private
    def customer_params
      params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :telephone_number, :email, :is_deleted, :birthday)
    end
end

app/views/admin/customers/edit.html.erb
<div class="edit-cats">
    <div class="col-xs-10 col-xs-10 col-xs-offset-1">
            <div class="row">
            <h2>会員情報編集</h2>
            <%= form_with model: @customer, url: admin_customer_path do |f| %>
                <table class="table table-hover table-inverse">
                    <tr>
                        <th class="col-xs-2"><%= f.label :会員ID %></th>
                        <td class="col-xs-10"><%= f.text_field :id, class:"form-control"%></td>
                    </tr>
                    <tr>
                        <th><%= f.label :氏名 %></th>
                        <td><%= f.text_field :last_name, class:"form-control" %><br>
                        <%= f.text_field :first_name, class:"form-control" %></td>
                    </tr>
                    <tr>
                        <th><%= f.label :電話番号 %></th>
                        <td><%= f.text_field :telephone_number, class:"form-control" %></td>
                    </tr>
                    <tr>
                        <th><%= f.label :メールアドレス %></th>
                        <td><%= f.text_field :email , class:"form-control"%></td>
                    </tr>
                    <tr>
                        <th><%= f.label :会員ステータス %></th>
                        <td><%= f.select :is_customer_status, [["登録済み","false"], ["退会済み","true"]], class:"form-control" %></td>
                    </tr>
                </table>
                <div class="row text-right">
                  <%= f.submit "変更を保存する" ,class: "btn btn-success " %>
                </div>
            <%end%>
            </div>
    </div>
</div>

app/views/admin/customers/index.html.erb
    <main>
        <body>
            <div class="row">
                <div class="col-xs-10 col-xs-offset-1">
                  <h2>会員一覧</h2>
                  
                  <table class="table table-hover table-inverse">
                      <thead>
                          <tr>
                              <th>会員</th>
                              <th>氏名</th>
                              <th>メールアドレス</th>
                              <th>ステータス</th>
                          </tr>
                      </thead>
                      <tbody>
                          <% @customers.each do |customer| %>
                            <tr>
                                <td><%= customer.id %></td>
                                <td><%= link_to customer.last_name + "　"  + customer.first_name,admin_customer_path(customer) %></td>
                                <td><%= customer.email %></td>
                                <td>
                                    <% if customer.is_deleted == false %>
                                    有効
                                    <% else %>
                                    退会
                                    <% end %>
                                </td>
                            </tr>
                          <%end%>
                          <%= paginate @customers %>
                      </tbody>
                  </table>
                  <div class="row">
                      <%= link_to "予約一覧", admin_reservations_path(@customer), class: 'btn btn-default' %>
                </div>
            </div>
        </body>
    </main>

app/views/admin/customers/show.html.erb
            <div class="row">
            <div class="col-xs-10 col-xs-offset-1">
                <h2>会員情報詳細</h2>
                  <table class="table table-hover table-inverse">
                    <tr>
                        <th class="col-xs-2">会員ID</th>
                        <td class="col-xs-10"><%= @customer.id %>
                        <% if @customer.is_deleted == false %>
                        <span class="label label-primary">
                            登録済み
                        </span>
                        <% else %>
                        <span class="label label-danger">
                            退会済み
                        </span>
                        <% end %>
                        </td>
                    <tr>
                        <td>氏名</td>
                        <td><%= @customer.last_name %>
                        <%= @customer.first_name %> </td>
                    </tr>
                    <tr>
                        <td>カナ</td>
                        <td><%=@customer.last_name_kana %>
                        <%= @customer.first_name_kana %> </td>
                    </tr>
                    <tr>
                        <td>電話番号</td>
                        <td><%= @customer.telephone_number %></td>
                    </tr>
                    <tr>
                        <td>メールアドレス</td>
                        <td><%= @customer.email %></td>
                    </tr>
                </table>
                <div class="row">
                    <%= link_to "編集する", edit_admin_customer_path(@customer), class: 'btn btn-default' %>
                    <%= link_to "一覧を見る", admin_customers_path, class: 'btn btn-default' %>
                </div>
            </div>
            </div>