config/routes.rb
Rails.application.routes.draw do
    
  get 'menu_items/index'
  # 顧客用
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  devise_scope :customer do
    post '/customers/sign_up', to: 'public/registrations#create', as: 'custom_registration'
    delete '/customers/sign_out' => 'devise/sessions#destroy'
  end

  root to: "public/homes#top"
  get '/about' => 'public/homes#about'
  
  scope module: 'customers' do
    resources :cats, only: [:show, :index]
    resources :menu_items, only: [:index]
  end
  
  namespace :public do
    get '/my_page', to: 'customers#show', as: 'my_page'#マイページ
    get 'customers/edit' => 'customers#edit'
    patch 'update' => 'customers#update'#会員情報編集画面
    get 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customer'#退会機能
    get 'quit' => 'customers#quit'#退会画面
    resources :cats, only: [:index, :show]#所属猫一覧画面、所属猫詳細画面
    resources :menu_items, only: [:index]#カフェメニュー一覧
    get '/reservations/new' => 'reservations#new', as: 'new_reservation'#予約情報入力画面
    post '/reservations' => 'reservations#create', as: 'reservations'
    get 'reservations/thanks' => 'reservations#thanks', as: 'thanks_reservation'#サンクス画面
    get 'my_page/reservations' => 'reservations#index', as: 'my_page_reservations'#予約情報入力画面
    resources :reservations, only: [:show]#予約情報確認画面
  end
  
  
  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  devise_scope :admin do
    delete '/admin/sign_out' => 'devise/sessions#destroy'
  end
   
  namespace :admin do
    root :to => 'homes#top'
    resources :customers, only: [:index, :show, :edit, :update, :destroy]#会員画面
    resources :cats, only: [:show, :index, :new, :create, :edit, :update, :destroy]#所属猫画面
    resources :menu_items, only: [:index, :new, :create, :edit, :update, :destroy]#カフェメニュー画面
    resources :reservations, only: [:index, :show]#予約一覧画面、予約詳細画面
    delete 'cats'=> 'cats#destroy'#登録猫削除画面
    delete 'menu_items'=> 'menu_items#destroy'
  end
end

app/models/cat.rb
class Cat < ApplicationRecord
    has_one_attached :image
    
    
    enum genders: { male: 0, female: 1 }
end

app/controllers/admin/cats_controller.rb
class Admin::CatsController < ApplicationController
    before_action :authenticate_admin!, only: [:create,:edit,:update,:index, :show, :new]
    
    def show
        @cat=Cat.find(params[:id])
    end
    
    def index
        @search=Cat.ransack(params[:q])
        @cats=@search.result.page(params[:page]).per(10)
        @cats_all=Cat.all
    end
    
    def new
        @cat=Cat.new
    end
    
    def create
        @cat=Cat.new(cat_params)
        @cat.image.attach(params[:cat][:image])
        if @cat.save
            redirect_to admin_cat_path(@cat)
        else
            redirect_to new_admin_cat_path
        end
    end
    
    def edit
        @cat=Cat.find(params[:id])
    end
    
    def update
        @cat=Cat.find(params[:id])
        @cat.image.attach(params[:cat][:image])
        if @cat.update(cat_params)
            redirect_to admin_cats_path(@cat)
            flash[:notice_update]="猫の情報を更新しました"
        else
            redirect_to edit_admin_cats_path(@cat)
        end
    end
    
    def destroy
        @cat=Cat.find(params[:id])
        @cat.destroy
        flash.now[:alert]="#{@cat.name}を削除しました"
        redirect_to admin_cats_path
    end
    
    private
    def cat_params
        params.require(:cat).permit(:name, :introduction, :genders, :image, :age, :cat_type)  
    end
end

app/views/admin/cats/edit.html.erb
            <div class="edit-cats">
                <div class="col-xs-10 col-xs-10 col-xs-offset-1">
                    <div class="row">
                        <%= form_with model: @cat, url: admin_cat_path do |f| %>
                            <h2>猫の登録情報編集</h2>
                            <div class= "item-new-form">
                                <%= f.file_field :image, accept: "image/*" %>
                            </div>
                          　<div class="product-img" style="margin-top: 20px;">
                                <%= image_tag @cat.image, size: "300x200" %>
                            </div>
                                <table class="table table-hover table-inverse">
                                    <tbody>
                                        <tr>
                                            <th>名前</th>
                                            <td><%= f.text_field :name, class: "form-control" %></td>
                                        </tr>
                                        <tr>
                                            <th>特徴</th>
                                            <td><%= f.text_area :introduction, class: "form-control" %></td>
                                        </tr>
                                        <tr>
                                            <th>年齢</th>
                                            <td style="white-space: nowrap;"><%= f.text_field :age, class: "form-control" %>才</td>
                                        </tr>
                                        <tr>
                                            <th>性別</th>
                                            <td><%= f.radio_button :genders, Cat.genders.key(0) %>
                                            <%= f.label :gender_male, "男の子" %></td>
                                            <td><%= f.radio_button :genders, Cat.genders.key(1) %>
                                            <%= f.label :gender_female, "女の子" %></td>
                                        </tr>
                                        <tr>
                                          <th>種類</th>
                                          <td><%= f.text_field :cat_type, class: "form-control" %></td>
                                        </tr>
                                    </tbody>
                                </table>
                                <div class="text-right">
                                    <%= f.submit "編集する", class: "btn btn-outline-dark " %>
                                    <%= link_to "削除する", admin_cat_path(@cat), method: :delete, class: "btn btn-outline-danger" %>
                                </div>
                        <%end%>
                    </div>
                </div>
            </div>
        </body>
    </main>
</html>
</html>

app/views/admin/cats/index.html.erb
            <div class="row">
                <div class="col-xs-10 col-xs-10 col-xs-offset-1">
                    <h2>Meow Manor Cafeの猫たち(管理者)</h2>
                    <table class="table table-hover table-inverse">
                        <thead>
                            <tr>
                                <th>CAT ID</th>
                                <th>NAME</th>
                                <th>TYPE</th>
                                <th>AGE</th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @cats.each do |cat| %>
                            <tr>
                                <td><%= cat.id %></td>
                                <td><%= link_to cat.name, admin_cat_path(cat) %></td>
                                <td><%= cat.cat_type %></td>
                                <td><%= cat.age %>才</td>
                                <td><%= link_to "編集する" ,edit_admin_cat_path(cat), class: "btn btn_-lg btn-outline-success" %></td>
                            </tr>
                            <%end%>
                        </tbody>
                    </table>
                    <div class="text_right">
                        <%= link_to "新規登録", new_admin_cat_path, class:"btn btn_-lg btn-outline-dark" %>
                    </div>
                    <%= paginate @cats %>
                </div>
            </div>

app/views/admin/cats/new.html.erb
          <div class="new-cats">
              <div class="col-md-10 col-md-offset-1 col-xs-10 col-xs-offset-1 mx-sm-auto">
                  <div class="row">
                    　<%= form_with model: @cat, url: admin_cats_path, method: :post, multipart: true do |f| %>
                        <div class="col-lg-4 col-xs-4">
                          <h4 class="cats-new-title" style="white-space: nowrap;">新しい猫を登録する</h4>
                          <div class="cat_new_form">
                            <%= f.file_field :image, accept: "image/*" %>
                          </div>
                        </div>
                            <table class="new-form-table">
                                <tbody>
                                    <tr>
                                        <th style="white-space: nowrap;"><span>名前</span></th>
                                          <td><%= f.text_field :name, class: "form-control" %></td>
                                        </tr>
                                        <tr>
                                          <th style="white-space: nowrap;"><span>特徴</span></th>
                                          <td><%= f.text_area :introduction, class: "form-control" %></td>
                                        </tr>
                                        <tr>
                                          <th style="white-space: nowrap;"><span>年齢</span></th>
                                          <td style="white-space: nowrap;"><%= f.text_field :age, class: "form-control" %>才</td>
                                        </tr>
                                        <tr>
                                          <th style="white-space: nowrap;"><span>性別</span></th>
                                          <td><%= f.radio_button :genders, Cat.genders.key(0) %>
                                          <%= f.label :gender_male, "男の子" %></td>
                                          <td style="white-space: nowrap;"><%= f.radio_button :genders, Cat.genders.key(1) %>
                                          <%= f.label :gender_female, "女の子" %></td>
                                        </tr>
                                        <tr>
                                          <th style="white-space: nowrap;"><span>種類</span></th>
                                          <td><%= f.text_field :cat_type, class: "form-control" %></td>
                                        </tr>
                                </tbody>
                            </table>
                            <%= f.submit '新規登録', class: "btn btn-outline-dark" %>
                        </div>
                      <%end%>
                  </div>
              </div>
          </div>
        </div>

app/views/admin/cats/show.html.erb
    <main>
      <body>
        <div class="show-cats">
          <h2>所属猫詳細(管理者)</h2>
          <div class="product-img" style="margin-top: 20px;">
            <%= image_tag @cat.image, size: "300x200" %>
          </div>
        </div>
          <table class="table table-hover table-inverse">
            <tbody>
                <td>名前</td>
                <td><%= @cat.name %></td>
              </tr>
              <tr>
                <td>特徴</td>
                <td><%= @cat.introduction %></td>
              </tr>
              <tr>
                <td>性別</td>
                <td><%= @cat.genders %></td>
              </tr>
              <tr>
                <td>種類</td>
                <td><%= @cat.cat_type %></td>
              </tr>
              <tr>
                <td>年齢</td>
                <td><%= @cat.age %></td>
              </tr>
              <tr>
                <td>出勤時間</td>
              </tr>
            </tbody>
          </table>
          <div class="col-md-offset-1 col-md-2 text-right">
            <%= link_to "編集する" ,edit_admin_cat_path(@cat), class: "btn btn-outline-dark" %>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-2">
          </div>
          <div class="col-xs-5">
          </div>
        </div>
      </body>
    </main>