config/routes.rb
Rails.application.routes.draw do
    
  get 'menu_items/index'
  # 顧客用
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  devise_scope :customer do
    post '/customers/sign_up', to: 'public/registrations#create', as: 'custom_registration'
    delete '/customers/sign_out' => 'devise/sessions#destroy'
  end

  root to: "public/homes#top"
  get '/about' => 'public/homes#about'
  
  scope module: 'customers' do
    resources :cats, only: [:show, :index]
    resources :menu_items, only: [:index]
  end
  
  namespace :public do
    get '/my_page', to: 'customers#show', as: 'my_page'#マイページ
    get 'customers/edit' => 'customers#edit'
    patch 'update' => 'customers#update'#会員情報編集画面
    get 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customer'#退会機能
    get 'quit' => 'customers#quit'#退会画面
    resources :cats, only: [:index, :show]#所属猫一覧画面、所属猫詳細画面
    resources :menu_items, only: [:index]#カフェメニュー一覧
    get '/reservations/new' => 'reservations#new', as: 'new_reservation'#予約情報入力画面
    post '/reservations' => 'reservations#create', as: 'reservations'
    get 'reservations/thanks' => 'reservations#thanks', as: 'thanks_reservation'#サンクス画面
    get 'my_page/reservations' => 'reservations#index', as: 'my_page_reservations'#予約情報入力画面
    resources :reservations, only: [:show]#予約情報確認画面
  end
  
  
  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  devise_scope :admin do
    delete '/admin/sign_out' => 'devise/sessions#destroy'
  end
   
  namespace :admin do
    root :to => 'homes#top'
    resources :customers, only: [:index, :show, :edit, :update, :destroy]#会員画面
    resources :cats, only: [:show, :index, :new, :create, :edit, :update, :destroy]#所属猫画面
    resources :menu_items, only: [:index, :new, :create, :edit, :update, :destroy]#カフェメニュー画面
    resources :reservations, only: [:index, :show]#予約一覧画面、予約詳細画面
    delete 'cats'=> 'cats#destroy'#登録猫削除画面
    delete 'menu_items'=> 'menu_items#destroy'
  end
end

app/views/layouts/_footer.html.erb
   <footer>
        <div class="container">
          <div class="small text-center text-muted" style="margin: 50px 0;">
              minamino © 2023  Meow Manor Cafe
          </div>
        </div>
   </footer>

app/views/layouts/_header.html.erb
<header>
        <nav class="navbar navbar-expand-lg p-1">
            <div class="container">
                    <a class="navbar-brand p-1" href="/" >
                        <%= image_tag('Meow Manor Cafe-logos2.png', size: '280x107') %>
                    </a>
                    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"><i class="fa-solid fa-paw"></i></span>
                    </button>
                <div class="collapse navbar-collapse " id="navbarNavDropdown">
                    <ul class="navbar-nav ml-auto">
                        <% if customer_signed_in? %>
                         <li class="nav-link" style="white-space: nowrap;"><%= link_to "MY PAGE", public_my_page_path, class: 'nav-link text-dark' %></li>
                         <li class="nav-link" style="white-space: nowrap;"><%= link_to "Meow Manor Cafeの猫たち", public_cats_path, class: 'nav-link text-dark' %></li>
                         <li class="nav-link" style="white-space: nowrap;"><%= link_to "CAFE MENU", public_menu_items_path, class: 'nav-link text-dark' %></li>
                         <li class="nav-link" style="white-space: nowrap;"><%= link_to "ABOUT", about_path, class: 'nav-link text-dark' %></li>
                         <li class="nav-link" style="white-space: nowrap;"><%= link_to "RESERVE", public_new_reservation_path, class: 'nav-link text-dark' %></li>
                         <li class="nav-link" style="white-space: nowrap;"><%= link_to "LOG OUT", destroy_customer_session_path, method: :delete, class: 'nav-link text-dark' %></li>
                        <% elsif admin_signed_in? %>
                         <li class="nav-link" style="white-space: nowrap;"><%= link_to "Meow Manor Cafeの猫たち", admin_cats_path, class: 'nav-link text-dark' %></li>
                         <li class="nav-link" style="white-space: nowrap;"><%= link_to "CAFE MENU", admin_menu_items_path, class: 'nav-link text-dark' %></li>
                         <li class="nav-link" style="white-space: nowrap;"><%= link_to "ABOUT", about_path, class: 'nav-link text-dark' %></li>
                         <li class="nav-link" style="white-space: nowrap;"><%= link_to "MEMBER", admin_customers_path, class: 'nav-link text-dark' %></li>
                         <li class="nav-link" style="white-space: nowrap;"><%= link_to "LOG OUT", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %></li>
                        <%else%>
                         <li class="nav-link" style="white-space: nowrap;"><%= link_to "Meow Manor Cafeの猫たち", public_cats_path, class: 'nav-link text-dark' %></li>
                         <li class="nav-link" style="white-space: nowrap;"><%= link_to "CAFE MENU", public_menu_items_path, class: 'nav-link text-dark' %></li>
                         <li class="nav-link" style="white-space: nowrap;"><%= link_to "SIGN UP", new_customer_registration_path, class: 'nav-link text-dark' %></li>
                         <li class="nav-link" style="white-space: nowrap;"><%= link_to "ABOUT", about_path, class: 'nav-link text-dark' %></li>
                         <li class="nav-link" style="white-space: nowrap;"><%= link_to "LOG IN", new_customer_session_path, class: 'nav-link text-dark' %></li>
                        <%end%>
                    </ul>
                </div>
            </div>
        </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="fontawesome-i2svg-active fontawesome-i2svg-complete">
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Zen+Maru+Gothic&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/91859b3e97.js" crossorigin="anonymous"></script>
    <title>MeowManorCafe</title>
  </head>
  <% if customer_signed_in? %>
  <body class="d-flex flex-column vh-100">
    <div class="shadow-sm">
      <%= render "layouts/header" %>
    </div>
    <div class="container">
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
  <% else %>
  <body class="d-flex flex-column vh-100">
    <div class="shadow-sm">
      <%= render "layouts/header" %>
    </div>
    <div class="container">
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
  <% end %>
</html>